### ISSUE TITLE
CLAP transaction fails sometimes

### ISSUE THREAD

**Issue by odelcroi** [calypsonet/keyple-java-demo-remote#14]
Sometimes CLAP transaction fails. 

Reproduce steps : 
- connect pcsc reader for sam
- connect pcsc reader for calypso card
- execute WaitTransactionTest#execute_wait_for_calypso_card()
- present a CLAP card multiple times

log file attached : 
- first transaction worked
- second failed

[tx-clap-fails.txt](https://github.com/calypsonet/keyple-java-demo-remote/files/7609343/tx-clap-fails.txt)

**Comment by jeanpierrefortune** [comment]
An issue (eclipse/keyple-service-java-lib#38) has been opened to fix this problem.

**Comment by jeanpierrefortune** [comment]
Fixed in #15
